name:                ptld-auction
version:             0.0.0.1
github:              "graninas/Pragmatic-Type-Level-Design/demo-apps/auction"
license:             BSD3
author:              "Alexander Granin"
maintainer:          "graninas@gmail.com"
copyright:           "Granin A.S. 2021"


default-extensions:
- GADTs
- RankNTypes
- DeriveFunctor
- DeriveGeneric
- OverloadedStrings
- LambdaCase
- MultiParamTypeClasses
- ExplicitNamespaces
- TypeApplications
- ScopedTypeVariables
- TypeOperators
- TypeFamilies
- DataKinds
- FlexibleContexts
- FlexibleInstances
- PatternSynonyms
- PolyKinds
- DefaultSignatures
- ConstraintKinds
- NamedFieldPuns
- TupleSections
- ViewPatterns
- MultiWayIf
- RecordWildCards

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- clock
- containers
- data-default
- directory
- entropy
- extra
- filepath
- fmt
- generic-lens
- gloss
- lens
- MonadRandom
- mtl
- newtype-generics
- random
- resource-pool
- resourcet
- scientific
- stm
- template-haskell
- text
- time
- time-units
- transformers
- universum
- uuid
- vector
- void
- ptld-lib


executables:
  tl-cell:
    main:                Main.hs
    source-dirs:         src/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    # - -O2

library:
  source-dirs:
  - src
  ghc-options:
  - -Wall


tests:
  auction-tests:
    main: Spec.hs
    source-dirs:
    - test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - ptld-lib
    - ptld-auction
