name:                ptld-book-samples
version:             0.0.0.1
github:              "graninas/Pragmatic-Type-Level-Design/book-samples"
license:             BSD3
author:              "Alexander Granin"
maintainer:          "graninas@gmail.com"
copyright:           "Granin A.S. 2021"


default-extensions:
- DeriveFunctor
- DeriveGeneric
- OverloadedStrings
- LambdaCase
- MultiParamTypeClasses
- ScopedTypeVariables
- ExplicitNamespaces
- NamedFieldPuns
- TupleSections
- ViewPatterns
- MultiWayIf
- RecordWildCards

dependencies:
- base >= 4.7 && < 5
- bytestring
- mtl
- time
- scientific
- containers
- free
- transformers
- template-haskell
- text
- newtype-generics
- uuid
- void
- random
- lens
- ptld-lib

library:
  source-dirs:
  - src
  ghc-options:
  - -Wall


tests:
  functional-tests:
    main: Spec.hs
    source-dirs:
    - test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - ptld-lib
    - ptld-book-samples
