# Makefile
CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++20
TARGET = AppendixB_FightClub_CPP_exist_program
SOURCES = main.cpp

all: $(TARGET)

$(TARGET): $(SOURCES)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SOURCES)

clean:
	rm -f "$(TARGET)"
