name:                Pragmatic-Type-Level-Design
version:             0.0.0.1
github:              "graninas/Pragmatic-Type-Level-Design"
license:             BSD3
author:              "Alexander Granin"
maintainer:          "graninas@gmail.com"
copyright:           "Granin A.S. 2020"


default-extensions:
# - NoImplicitPrelude
- GADTs
- RankNTypes
- DeriveFunctor
- DeriveGeneric
- OverloadedStrings
- LambdaCase
- MultiParamTypeClasses
- ExplicitNamespaces
- TypeApplications
- ScopedTypeVariables
- TypeOperators
- TypeFamilies
- DataKinds
- FlexibleContexts
- FlexibleInstances
- PatternSynonyms
- PolyKinds
- DefaultSignatures
- ConstraintKinds
- NamedFieldPuns
- TupleSections
- ViewPatterns
- MultiWayIf
- RecordWildCards

dependencies:
- base >= 4.7 && < 5
- bytestring
- mtl
- time
- scientific
- containers
- free
- transformers
- template-haskell
- text
- newtype-generics
- uuid

library:
  source-dirs:
  - src
  ghc-options:
  - -Wall


tests:
  functional-tests:
    main: Spec.hs
    source-dirs:
    - test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - Pragmatic-Type-Level-Design
