
resolver: lts-16.16

packages:
- lib
- book-samples
- demo-apps/hcell
- demo-apps/type-class-automaton1
- demo-apps/type-class-automaton2
- demo-apps/type-class-automaton3
- demo-apps/auction
- demo-apps/car
