use tl_list_lib::tl_list;
use tl_str_macro::tl_str;

use crate::master::language::model::{*};
use crate::master::language::extensions::{*};


pub struct GameType;
pub struct BoardType;

// This size of the model is the maximum under the default
// compiler settings.
pub type BigTypeLevelModel = tl_list![IRoute,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/start"),
            tl_list![IClause],
            tl_list![IFormat, JSON],
            DataType<GameType>>,
      Route<POST, tl_str!("/move"),
            tl_list![IClause,
                     Capture<tl_str!("id"), StringType>,
                     Capture<tl_str!("sign"), StringType>,
                     QueryParam<tl_str!("h"), IntType>,
                     QueryParam<tl_str!("v"), IntType>],
            tl_list![IFormat, JSON],
            StringType>,
      Route<GET, tl_str!("/board"),
            tl_list![IClause,
                     Capture<tl_str!("id"), StringType>],
            tl_list![IFormat, JSON],
            DataType<BoardType>>];
