name:                minefield
version:             1.0.0.0
license:             BSD3
author:              "Alexander Granin"
maintainer:          "graninas@gmail.com"
copyright:           "Granin A.S. 2024"

default-extensions:
- DeriveFunctor
- DeriveGeneric
- OverloadedStrings
- ScopedTypeVariables
- LambdaCase
- ExplicitNamespaces
- NamedFieldPuns
- TupleSections
- ViewPatterns
- MultiWayIf
- RecordWildCards
- InstanceSigs
- NoImplicitPrelude

- DataKinds
- TypeOperators
- FunctionalDependencies
- TypeFamilies
- FlexibleContexts
- FlexibleInstances
- ScopedTypeVariables
- PolyKinds
- KindSignatures
- TypeApplications
- GADTs


dependencies:
- base >= 4.7 && < 5
- bytestring
- mtl
- time
- scientific
- containers
- free
- transformers
- template-haskell
- text
- newtype-generics
- uuid
- void
- random
- lens
- ptld-lib
- ghc-prim

library:
  source-dirs:
  - src
  ghc-options:
  - -Wall

executables:
  minefield:
    main:                Main.hs
    source-dirs:         ./src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall

tests:
  functional:
    main: Spec.hs
    source-dirs:
    - test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - minefield
