[package]
name = "rsc1p3_type_level_interfaces"
version = "0.1.0"
edition = "2021"

[dependencies]
gensym = "0.1.0"
type_level = { path = "./type_level" }
tl_list_lib = { path = "./tl_list_lib" }
tl_str_list = { path = "./tl_str_list" }
tl_str_macro = { path = "./tl_str_macro" }
