name:                ptld-lib
version:             0.0.0.1
license:             BSD3
author:              "Alexander Granin"
maintainer:          "graninas@gmail.com"
copyright:           "Granin A.S. 2024"


default-extensions:
- DeriveFunctor
- DeriveGeneric
- OverloadedStrings
- LambdaCase
- MultiParamTypeClasses
- ScopedTypeVariables
- ExplicitNamespaces
- NamedFieldPuns
- TupleSections
- ViewPatterns
- MultiWayIf
- RecordWildCards

dependencies:
- base >= 4.7 && < 5
- bytestring
- mtl
- time
- scientific
- containers
- free
- transformers
- template-haskell
- text
- newtype-generics
- uuid
- void
- random
- lens
- stm
- universum
- aeson
- hspec



library:
  source-dirs:
  - src
  ghc-options:
  - -Wall



tests:
  ptld-lib-tests:
    main: Spec.hs
    source-dirs:
    - test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ptld-lib
