[package]
name = "rsc2p2p4_type_level_strings"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.10"
tl_str_list = { path = "./tl_str_list" }
tl_str_macro = { path = "./tl_str_macro" }
