
resolver: lts-21.15

packages:
- BookSamples/CH01/Section1p1v1
- BookSamples/CH01/Section1p1v2
- BookSamples/CH01/Section2p1
- BookSamples/CH01/Section2p2
- BookSamples/CH01/Section2p4

- BookSamples/CH02/Section2p1
- BookSamples/CH02/Section2p2

- BookSamples/CH03/Section1p1
- BookSamples/CH03/Section1p2
- BookSamples/CH03/Section1p3
- BookSamples/CH03/Section1p4
- BookSamples/CH03/Section1p5
- BookSamples/CH03/Section2p2

- BookSamples/CH04/Section1p1

