
resolver: lts-21.15

packages:
- BookSamples/CH01/Section1p1v1
- BookSamples/CH01/Section1p1v2
- BookSamples/CH01/Section2p1
- BookSamples/CH01/Section2p2
- BookSamples/CH01/Section2p4

- BookSamples/CH02/Section2p1
- BookSamples/CH02/Section2p2

- BookSamples/CH03/Section1p1
- BookSamples/CH03/Section1p2
- BookSamples/CH03/Section1p3
- BookSamples/CH03/Section1p4
- BookSamples/CH03/Section1p5
- BookSamples/CH03/Section2p2

- BookSamples/CH04/Section1p2
- BookSamples/CH04/Section2
- BookSamples/CH04/Section2p1
- BookSamples/CH04/Section2p5

- BookSamples/CH05
- BookSamples/CH07
- BookSamples/CH08/Section1p1
- BookSamples/CH08/Section1p2
- BookSamples/CH08/Section1p3

- BookSamples/demo-apps/ptld-lib
- BookSamples/demo-apps/ptld-auction
- BookSamples/demo-apps/turing-machine
- BookSamples/demo-apps/minefield

- BookSamples/appendices/AppendixB_FightClub/haskell_exist
- BookSamples/appendices/AppendixB_FightClub/haskell_value
- BookSamples/appendices/AppendixC_MythologizedCorrectness

allow-newer: true

extra-deps:
- strong-path-1.1.4.0@sha256:d43a7e9231055714cc21a596da245d9d0613623c1cf3624a4671bd1fb2cf76ea,2247
